const ItemIdentifier = require("./ItemIdentifier");
const Item = require("./Item");
const ItemIds = require("./ItemIds");
module.exports = {
    AIR: new Item(new ItemIdentifier(0, 0), "Air"),
    APPLE: new Item(new ItemIdentifier(ItemIds.APPLE, 0), "Apple"),
    GOLDEN_APPLE: new Item(new ItemIdentifier(ItemIds.GOLDEN_APPLE, 0), "Golden Apple"),
    ENCHANTED_GOLDEN_APPLE: new Item(new ItemIdentifier(ItemIds.ENCHANTED_GOLDEN_APPLE, 0), "Enchanted Golden Apple"),
    MUSHROOM_STEW: new Item(new ItemIdentifier(ItemIds.MUSHROOM_STEW, 0), "Mushroom Stew"),
    BREAD: new Item(new ItemIdentifier(ItemIds.BREAD, 0), "Bread"),
    PORKCHOP: new Item(new ItemIdentifier(ItemIds.PORKCHOP, 0), "Porkchop"),
    COOKED_PORKCHOP: new Item(new ItemIdentifier(ItemIds.COOKED_PORKCHOP, 0), "Cooked Porkchop"),
    COD: new Item(new ItemIdentifier(ItemIds.COD, 0), "Cod"),
    SALMON: new Item(new ItemIdentifier(ItemIds.SALMON, 0), "Salmon"),
    TROPICAL_FISH: new Item(new ItemIdentifier(ItemIds.TROPICAL_FISH, 0), "Tropical Fish"),
    PUFFERFISH: new Item(new ItemIdentifier(ItemIds.PUFFERFISH, 0), "Pufferfish"),
    COOKED_COD: new Item(new ItemIdentifier(ItemIds.COOKED_COD, 0), "Cooked Cod"),
    COOKED_SALMON: new Item(new ItemIdentifier(ItemIds.COOKED_SALMON, 0), "Cooked Salmon"),
    DRIED_KELP: new Item(new ItemIdentifier(ItemIds.DRIED_KELP, 0), "Dried Kelp"),
    COOKIE: new Item(new ItemIdentifier(ItemIds.COOKIE, 0), "Cookie"),
    MELON_SLICE: new Item(new ItemIdentifier(ItemIds.MELON_SLICE, 0), "Melon Slice"),
    BEEF: new Item(new ItemIdentifier(ItemIds.BEEF, 0), "Beef"),
    COOKED_BEEF: new Item(new ItemIdentifier(ItemIds.COOKED_BEEF, 0), "Cooked Beef"),
    CHICKEN: new Item(new ItemIdentifier(ItemIds.CHICKEN, 0), "Chicken"),
    COOKED_CHICKEN: new Item(new ItemIdentifier(ItemIds.COOKED_CHICKEN, 0), "Cooked Chicken"),
    ROTTEN_FLESH: new Item(new ItemIdentifier(ItemIds.ROTTEN_FLESH, 0), "Rotten Flesh"),
    SPIDER_EYE: new Item(new ItemIdentifier(ItemIds.SPIDER_EYE, 0), "Spider Eye"),
    CARROT: new Item(new ItemIdentifier(ItemIds.CARROT, 0), "Carrot"),
    POTATO: new Item(new ItemIdentifier(ItemIds.POTATO, 0), "Potato"),
    BAKED_POTATO: new Item(new ItemIdentifier(ItemIds.BAKED_POTATO, 0), "Baked Potato"),
    POISONOUS_POTATO: new Item(new ItemIdentifier(ItemIds.POISONOUS_POTATO, 0), "Poisonous Potato"),
    GOLDEN_CARROT: new Item(new ItemIdentifier(ItemIds.GOLDEN_CARROT, 0), "Golden Carrot"),
    PUMPKIN_PIE: new Item(new ItemIdentifier(ItemIds.PUMPKIN_PIE, 0), "Pumpkin Pie"),
    BEETROOT: new Item(new ItemIdentifier(ItemIds.BEETROOT, 0), "Beetroot"),
    BEETROOT_SOUP: new Item(new ItemIdentifier(ItemIds.BEETROOT_SOUP, 0), "Beetroot Soup"),
    SWEET_BERRIES: new Item(new ItemIdentifier(ItemIds.SWEET_BERRIES, 0), "Sweet Berries"),
    RABBIT: new Item(new ItemIdentifier(ItemIds.RABBIT, 0), "Rabbit"),
    COOKED_RABBIT: new Item(new ItemIdentifier(ItemIds.COOKED_RABBIT, 0), "Cooked Rabbit"),
    RABBIT_STEW: new Item(new ItemIdentifier(ItemIds.RABBIT_STEW, 0), "Rabbit Stew"),
    WHEAT_SEEDS: new Item(new ItemIdentifier(ItemIds.WHEAT_SEEDS, 0), "Wheat Seeds"),
    PUMPKIN_SEEDS: new Item(new ItemIdentifier(ItemIds.PUMPKIN_SEEDS, 0), "Pumpkin Seeds"),
    MELON_SEEDS: new Item(new ItemIdentifier(ItemIds.MELON_SEEDS, 0), "Melon Seeds"),
    NETHER_WART: new Item(new ItemIdentifier(ItemIds.NETHER_WART, 0), "Nether Wart"),
    BEETROOT_SEEDS: new Item(new ItemIdentifier(ItemIds.BEETROOT_SEEDS, 0), "Beetroot Seeds"),
    IRON_SHOVEL: new Item(new ItemIdentifier(ItemIds.IRON_SHOVEL, 0), "Iron Shovel"),
    IRON_PICKAXE: new Item(new ItemIdentifier(ItemIds.IRON_PICKAXE, 0), "Iron Pickaxe"),
    IRON_AXE: new Item(new ItemIdentifier(ItemIds.IRON_AXE, 0), "Iron Axe"),
    FLINT_AND_STEEL: new Item(new ItemIdentifier(ItemIds.FLINT_AND_STEEL, 0), "Flint And Steel"),
    BOW: new Item(new ItemIdentifier(ItemIds.BOW, 0), "Bow"),
    ARROW: new Item(new ItemIdentifier(ItemIds.ARROW, 0), "Arrow"),
    COAL: new Item(new ItemIdentifier(ItemIds.COAL, 0), "Coal"),
    CHARCOAL: new Item(new ItemIdentifier(ItemIds.CHARCOAL, 0), "Charcoal"),
    DIAMOND: new Item(new ItemIdentifier(ItemIds.DIAMOND, 0), "Diamond"),
    IRON_INGOT: new Item(new ItemIdentifier(ItemIds.IRON_INGOT, 0), "Iron Ingot"),
    GOLD_INGOT: new Item(new ItemIdentifier(ItemIds.GOLD_INGOT, 0), "Gold Ingot"),
    IRON_SWORD: new Item(new ItemIdentifier(ItemIds.IRON_SWORD, 0), "Iron Sword"),
    WOODEN_SWORD: new Item(new ItemIdentifier(ItemIds.WOODEN_SWORD, 0), "Wooden Sword"),
    WOODEN_SHOVEL: new Item(new ItemIdentifier(ItemIds.WOODEN_SHOVEL, 0), "Wooden Shovel"),
    WOODEN_PICKAXE: new Item(new ItemIdentifier(ItemIds.WOODEN_PICKAXE, 0), "Wooden Pickaxe"),
    WOODEN_AXE: new Item(new ItemIdentifier(ItemIds.WOODEN_AXE, 0), "Wooden Axe"),
    STONE_SWORD: new Item(new ItemIdentifier(ItemIds.STONE_SWORD, 0), "Stone Sword"),
    STONE_SHOVEL: new Item(new ItemIdentifier(ItemIds.STONE_SHOVEL, 0), "Stone Shovel"),
    STONE_PICKAXE: new Item(new ItemIdentifier(ItemIds.STONE_PICKAXE, 0), "Stone Pickaxe"),
    STONE_AXE: new Item(new ItemIdentifier(ItemIds.STONE_AXE, 0), "Stone Axe"),
    DIAMOND_SWORD: new Item(new ItemIdentifier(ItemIds.DIAMOND_SWORD, 0), "Diamond Sword"),
    DIAMOND_SHOVEL: new Item(new ItemIdentifier(ItemIds.DIAMOND_SHOVEL, 0), "Diamond Shovel"),
    DIAMOND_PICKAXE: new Item(new ItemIdentifier(ItemIds.DIAMOND_PICKAXE, 0), "Diamond Pickaxe"),
    DIAMOND_AXE: new Item(new ItemIdentifier(ItemIds.DIAMOND_AXE, 0), "Diamond Axe"),
    STICK: new Item(new ItemIdentifier(ItemIds.STICK, 0), "Stick"),
    BOWL: new Item(new ItemIdentifier(ItemIds.BOWL, 0), "Bowl"),
    GOLDEN_SWORD: new Item(new ItemIdentifier(ItemIds.GOLDEN_SWORD, 0), "Golden Sword"),
    GOLDEN_SHOVEL: new Item(new ItemIdentifier(ItemIds.GOLDEN_SHOVEL, 0), "Golden Shovel"),
    GOLDEN_PICKAXE: new Item(new ItemIdentifier(ItemIds.GOLDEN_PICKAXE, 0), "Golden Pickaxe"),
    GOLDEN_AXE: new Item(new ItemIdentifier(ItemIds.GOLDEN_AXE, 0), "Golden Axe"),
    STRING: new Item(new ItemIdentifier(ItemIds.STRING, 0), "String"),
    FEATHER: new Item(new ItemIdentifier(ItemIds.FEATHER, 0), "Feather"),
    GUNPOWDER: new Item(new ItemIdentifier(ItemIds.GUNPOWDER, 0), "Gunpowder"),
    WOODEN_HOE: new Item(new ItemIdentifier(ItemIds.WOODEN_HOE, 0), "Wooden Hoe"),
    STONE_HOE: new Item(new ItemIdentifier(ItemIds.STONE_HOE, 0), "Stone Hoe"),
    IRON_HOE: new Item(new ItemIdentifier(ItemIds.IRON_HOE, 0), "Iron Hoe"),
    DIAMOND_HOE: new Item(new ItemIdentifier(ItemIds.DIAMOND_HOE, 0), "Diamond Hoe"),
    GOLDEN_HOE: new Item(new ItemIdentifier(ItemIds.GOLDEN_HOE, 0), "Golden Hoe"),
    WHEAT: new Item(new ItemIdentifier(ItemIds.WHEAT, 0), "Wheat"),
    LEATHER_HELMET: new Item(new ItemIdentifier(ItemIds.LEATHER_HELMET, 0), "Leather Helmet"),
    LEATHER_CHESTPLATE: new Item(new ItemIdentifier(ItemIds.LEATHER_CHESTPLATE, 0), "Leather Chestplate"),
    LEATHER_LEGGINGS: new Item(new ItemIdentifier(ItemIds.LEATHER_LEGGINGS, 0), "Leather Leggings"),
    LEATHER_BOOTS: new Item(new ItemIdentifier(ItemIds.LEATHER_BOOTS, 0), "Leather Boots"),
    CHAINMAIL_HELMET: new Item(new ItemIdentifier(ItemIds.CHAINMAIL_HELMET, 0), "Chainmail Helmet"),
    CHAINMAIL_CHESTPLATE: new Item(new ItemIdentifier(ItemIds.CHAINMAIL_CHESTPLATE, 0), "Chainmail Chestplate"),
    CHAINMAIL_LEGGINGS: new Item(new ItemIdentifier(ItemIds.CHAINMAIL_LEGGINGS, 0), "Chainmail Leggings"),
    CHAINMAIL_BOOTS: new Item(new ItemIdentifier(ItemIds.CHAINMAIL_BOOTS, 0), "Chainmail Boots"),
    IRON_HELMET: new Item(new ItemIdentifier(ItemIds.IRON_HELMET, 0), "Iron Helmet"),
    IRON_CHESTPLATE: new Item(new ItemIdentifier(ItemIds.IRON_CHESTPLATE, 0), "Iron Chestplate"),
    IRON_LEGGINGS: new Item(new ItemIdentifier(ItemIds.IRON_LEGGINGS, 0), "Iron Leggings"),
    IRON_BOOTS: new Item(new ItemIdentifier(ItemIds.IRON_BOOTS, 0), "Iron Boots"),
    DIAMOND_HELMET: new Item(new ItemIdentifier(ItemIds.DIAMOND_HELMET, 0), "Diamond Helmet"),
    DIAMOND_CHESTPLATE: new Item(new ItemIdentifier(ItemIds.DIAMOND_CHESTPLATE, 0), "Diamond Chestplate"),
    DIAMOND_LEGGINGS: new Item(new ItemIdentifier(ItemIds.DIAMOND_LEGGINGS, 0), "Diamond Leggings"),
    DIAMOND_BOOTS: new Item(new ItemIdentifier(ItemIds.DIAMOND_BOOTS, 0), "Diamond Boots"),
    GOLDEN_HELMET: new Item(new ItemIdentifier(ItemIds.GOLDEN_HELMET, 0), "Golden Helmet"),
    GOLDEN_CHESTPLATE: new Item(new ItemIdentifier(ItemIds.GOLDEN_CHESTPLATE, 0), "Golden Chestplate"),
    GOLDEN_LEGGINGS: new Item(new ItemIdentifier(ItemIds.GOLDEN_LEGGINGS, 0), "Golden Leggings"),
    GOLDEN_BOOTS: new Item(new ItemIdentifier(ItemIds.GOLDEN_BOOTS, 0), "Golden Boots"),
    SHIELD: new Item(new ItemIdentifier(ItemIds.SHIELD, 0), "Shield"),
    FLINT: new Item(new ItemIdentifier(ItemIds.FLINT, 0), "Flint"),
    PAINTING: new Item(new ItemIdentifier(ItemIds.PAINTING, 0), "Painting"),
    OAK_SIGN: new Item(new ItemIdentifier(ItemIds.OAK_SIGN, 0), "Oak Sign"),
    WOODEN_DOOR: new Item(new ItemIdentifier(ItemIds.WOODEN_DOOR, 0), "Wooden Door"),
    BUCKET: new Item(new ItemIdentifier(ItemIds.BUCKET, 0), "Bucket"),
    MILK_BUCKET: new Item(new ItemIdentifier(ItemIds.MILK_BUCKET, 0), "Milk Bucket"),
    WATER_BUCKET: new Item(new ItemIdentifier(ItemIds.WATER_BUCKET, 0), "Water Bucket"),
    LAVA_BUCKET: new Item(new ItemIdentifier(ItemIds.LAVA_BUCKET, 0), "Lava Bucket"),
    COD_BUCKET: new Item(new ItemIdentifier(ItemIds.COD_BUCKET, 0), "Cod Bucket"),
    SALMON_BUCKET: new Item(new ItemIdentifier(ItemIds.SALMON_BUCKET, 0), "Salmon Bucket"),
    TROPICAL_FISH_BUCKET: new Item(new ItemIdentifier(ItemIds.TROPICAL_FISH_BUCKET, 0), "Tropical Fish Bucket"),
    PUFFERFISH_BUCKET: new Item(new ItemIdentifier(ItemIds.PUFFERFISH_BUCKET, 0), "Pufferfish Bucket"),
    POWDER_SNOW_BUCKET: new Item(new ItemIdentifier(ItemIds.POWDER_SNOW_BUCKET, 0), "Powder Snow Bucket"),
    AXOLOTL_BUCKET: new Item(new ItemIdentifier(ItemIds.AXOLOTL_BUCKET, 0), "Axolotl Bucket"),
    MINECART: new Item(new ItemIdentifier(ItemIds.MINECART, 0), "Minecart"),
    SADDLE: new Item(new ItemIdentifier(ItemIds.SADDLE, 0), "Saddle"),
    IRON_DOOR: new Item(new ItemIdentifier(ItemIds.IRON_DOOR, 0), "Iron Door"),
    REDSTONE: new Item(new ItemIdentifier(ItemIds.REDSTONE, 0), "Redstone"),
    SNOWBALL: new Item(new ItemIdentifier(ItemIds.SNOWBALL, 0), "Snowball"),
    OAK_BOAT: new Item(new ItemIdentifier(ItemIds.OAK_BOAT, 0), "Oak Boat"),
    BIRCH_BOAT: new Item(new ItemIdentifier(ItemIds.BIRCH_BOAT, 0), "Birch Boat"),
    JUNGLE_BOAT: new Item(new ItemIdentifier(ItemIds.JUNGLE_BOAT, 0), "Jungle Boat"),
    SPRUCE_BOAT: new Item(new ItemIdentifier(ItemIds.SPRUCE_BOAT, 0), "Spruce Boat"),
    ACACIA_BOAT: new Item(new ItemIdentifier(ItemIds.ACACIA_BOAT, 0), "Acacia Boat"),
    DARK_OAK_BOAT: new Item(new ItemIdentifier(ItemIds.DARK_OAK_BOAT, 0), "Dark Oak Boat"),
    LEATHER: new Item(new ItemIdentifier(ItemIds.LEATHER, 0), "Leather"),
    KELP: new Item(new ItemIdentifier(ItemIds.KELP, 0), "Kelp"),
    BRICK: new Item(new ItemIdentifier(ItemIds.BRICK, 0), "Brick"),
    CLAY_BALL: new Item(new ItemIdentifier(ItemIds.CLAY_BALL, 0), "Clay Ball"),
    SUGAR_CANE: new Item(new ItemIdentifier(ItemIds.SUGAR_CANE, 0), "Sugar Cane"),
    PAPER: new Item(new ItemIdentifier(ItemIds.PAPER, 0), "Paper"),
    BOOK: new Item(new ItemIdentifier(ItemIds.BOOK, 0), "Book"),
    SLIME_BALL: new Item(new ItemIdentifier(ItemIds.SLIME_BALL, 0), "Slime Ball"),
    CHEST_MINECART: new Item(new ItemIdentifier(ItemIds.CHEST_MINECART, 0), "Chest Minecart"),
    EGG: new Item(new ItemIdentifier(ItemIds.EGG, 0), "Egg"),
    COMPASS: new Item(new ItemIdentifier(ItemIds.COMPASS, 0), "Compass"),
    FISHING_ROD: new Item(new ItemIdentifier(ItemIds.FISHING_ROD, 0), "Fishing Rod"),
    CLOCK: new Item(new ItemIdentifier(ItemIds.CLOCK, 0), "Clock"),
    GLOWSTONE_DUST: new Item(new ItemIdentifier(ItemIds.GLOWSTONE_DUST, 0), "Glowstone Dust"),
    BLACK_DYE: new Item(new ItemIdentifier(ItemIds.BLACK_DYE, 0), "Black Dye"),
    RED_DYE: new Item(new ItemIdentifier(ItemIds.RED_DYE, 0), "Red Dye"),
    GREEN_DYE: new Item(new ItemIdentifier(ItemIds.GREEN_DYE, 0), "Green Dye"),
    BROWN_DYE: new Item(new ItemIdentifier(ItemIds.BROWN_DYE, 0), "Brown Dye"),
    BLUE_DYE: new Item(new ItemIdentifier(ItemIds.BLUE_DYE, 0), "Blue Dye"),
    PURPLE_DYE: new Item(new ItemIdentifier(ItemIds.PURPLE_DYE, 0), "Purple Dye"),
    CYAN_DYE: new Item(new ItemIdentifier(ItemIds.CYAN_DYE, 0), "Cyan Dye"),
    LIGHT_GRAY_DYE: new Item(new ItemIdentifier(ItemIds.LIGHT_GRAY_DYE, 0), "Light Gray Dye"),
    GRAY_DYE: new Item(new ItemIdentifier(ItemIds.GRAY_DYE, 0), "Gray Dye"),
    PINK_DYE: new Item(new ItemIdentifier(ItemIds.PINK_DYE, 0), "Pink Dye"),
    LIME_DYE: new Item(new ItemIdentifier(ItemIds.LIME_DYE, 0), "Lime Dye"),
    YELLOW_DYE: new Item(new ItemIdentifier(ItemIds.YELLOW_DYE, 0), "Yellow Dye"),
    LIGHT_BLUE_DYE: new Item(new ItemIdentifier(ItemIds.LIGHT_BLUE_DYE, 0), "Light Blue Dye"),
    MAGENTA_DYE: new Item(new ItemIdentifier(ItemIds.MAGENTA_DYE, 0), "Magenta Dye"),
    ORANGE_DYE: new Item(new ItemIdentifier(ItemIds.ORANGE_DYE, 0), "Orange Dye"),
    WHITE_DYE: new Item(new ItemIdentifier(ItemIds.WHITE_DYE, 0), "White Dye"),
    BONE_MEAL: new Item(new ItemIdentifier(ItemIds.BONE_MEAL, 0), "Bone Meal"),
    COCOA_BEANS: new Item(new ItemIdentifier(ItemIds.COCOA_BEANS, 0), "Cocoa Beans"),
    INK_SAC: new Item(new ItemIdentifier(ItemIds.INK_SAC, 0), "Ink Sac"),
    LAPIS_LAZULI: new Item(new ItemIdentifier(ItemIds.LAPIS_LAZULI, 0), "Lapis Lazuli"),
    BONE: new Item(new ItemIdentifier(ItemIds.BONE, 0), "Bone"),
    SUGAR: new Item(new ItemIdentifier(ItemIds.SUGAR, 0), "Sugar"),
    CAKE: new Item(new ItemIdentifier(ItemIds.CAKE, 0), "Cake"),
    BED: new Item(new ItemIdentifier(ItemIds.BED, 0), "Bed"),
    REPEATER: new Item(new ItemIdentifier(ItemIds.REPEATER, 0), "Repeater"),
    FILLED_MAP: new Item(new ItemIdentifier(ItemIds.FILLED_MAP, 0), "Filled Map"),
    SHEARS: new Item(new ItemIdentifier(ItemIds.SHEARS, 0), "Shears"),
    ENDER_PEARL: new Item(new ItemIdentifier(ItemIds.ENDER_PEARL, 0), "Ender Pearl"),
    BLAZE_ROD: new Item(new ItemIdentifier(ItemIds.BLAZE_ROD, 0), "Blaze Rod"),
    GHAST_TEAR: new Item(new ItemIdentifier(ItemIds.GHAST_TEAR, 0), "Ghast Tear"),
    GOLD_NUGGET: new Item(new ItemIdentifier(ItemIds.GOLD_NUGGET, 0), "Gold Nugget"),
    POTION: new Item(new ItemIdentifier(ItemIds.POTION, 0), "Potion"),
    GLASS_BOTTLE: new Item(new ItemIdentifier(ItemIds.GLASS_BOTTLE, 0), "Glass Bottle"),
    FERMENTED_SPIDER_EYE: new Item(new ItemIdentifier(ItemIds.FERMENTED_SPIDER_EYE, 0), "Fermented Spider Eye"),
    BLAZE_POWDER: new Item(new ItemIdentifier(ItemIds.BLAZE_POWDER, 0), "Blaze Powder"),
    MAGMA_CREAM: new Item(new ItemIdentifier(ItemIds.MAGMA_CREAM, 0), "Magma Cream"),
    BREWING_STAND: new Item(new ItemIdentifier(ItemIds.BREWING_STAND, 0), "Brewing Stand"),
    CAULDRON: new Item(new ItemIdentifier(ItemIds.CAULDRON, 0), "Cauldron"),
    ENDER_EYE: new Item(new ItemIdentifier(ItemIds.ENDER_EYE, 0), "Ender Eye"),
    GLISTERING_MELON_SLICE: new Item(new ItemIdentifier(ItemIds.GLISTERING_MELON_SLICE, 0), "Glistering Melon Slice"),
    CHICKEN_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.CHICKEN_SPAWN_EGG, 0), "Chicken Spawn Egg"),
    COW_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.COW_SPAWN_EGG, 0), "Cow Spawn Egg"),
    PIG_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.PIG_SPAWN_EGG, 0), "Pig Spawn Egg"),
    SHEEP_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.SHEEP_SPAWN_EGG, 0), "Sheep Spawn Egg"),
    WOLF_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.WOLF_SPAWN_EGG, 0), "Wolf Spawn Egg"),
    MOOSHROOM_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.MOOSHROOM_SPAWN_EGG, 0), "Mooshroom Spawn Egg"),
    CREEPER_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.CREEPER_SPAWN_EGG, 0), "Creeper Spawn Egg"),
    ENDERMAN_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.ENDERMAN_SPAWN_EGG, 0), "Enderman Spawn Egg"),
    SILVERFISH_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.SILVERFISH_SPAWN_EGG, 0), "Silverfish Spawn Egg"),
    SKELETON_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.SKELETON_SPAWN_EGG, 0), "Skeleton Spawn Egg"),
    SLIME_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.SLIME_SPAWN_EGG, 0), "Slime Spawn Egg"),
    SPIDER_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.SPIDER_SPAWN_EGG, 0), "Spider Spawn Egg"),
    ZOMBIE_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.ZOMBIE_SPAWN_EGG, 0), "Zombie Spawn Egg"),
    ZOMBIE_PIGMAN_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.ZOMBIE_PIGMAN_SPAWN_EGG, 0), "Zombie Pigman Spawn Egg"),
    VILLAGER_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.VILLAGER_SPAWN_EGG, 0), "Villager Spawn Egg"),
    SQUID_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.SQUID_SPAWN_EGG, 0), "Squid Spawn Egg"),
    OCELOT_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.OCELOT_SPAWN_EGG, 0), "Ocelot Spawn Egg"),
    WITCH_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.WITCH_SPAWN_EGG, 0), "Witch Spawn Egg"),
    BAT_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.BAT_SPAWN_EGG, 0), "Bat Spawn Egg"),
    GHAST_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.GHAST_SPAWN_EGG, 0), "Ghast Spawn Egg"),
    MAGMA_CUBE_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.MAGMA_CUBE_SPAWN_EGG, 0), "Magma Cube Spawn Egg"),
    BLAZE_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.BLAZE_SPAWN_EGG, 0), "Blaze Spawn Egg"),
    CAVE_SPIDER_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.CAVE_SPIDER_SPAWN_EGG, 0), "Cave Spider Spawn Egg"),
    HORSE_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.HORSE_SPAWN_EGG, 0), "Horse Spawn Egg"),
    RABBIT_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.RABBIT_SPAWN_EGG, 0), "Rabbit Spawn Egg"),
    ENDERMITE_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.ENDERMITE_SPAWN_EGG, 0), "Endermite Spawn Egg"),
    GUARDIAN_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.GUARDIAN_SPAWN_EGG, 0), "Guardian Spawn Egg"),
    STRAY_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.STRAY_SPAWN_EGG, 0), "Stray Spawn Egg"),
    HUSK_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.HUSK_SPAWN_EGG, 0), "Husk Spawn Egg"),
    WITHER_SKELETON_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.WITHER_SKELETON_SPAWN_EGG, 0), "Wither Skeleton Spawn Egg"),
    DONKEY_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.DONKEY_SPAWN_EGG, 0), "Donkey Spawn Egg"),
    MULE_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.MULE_SPAWN_EGG, 0), "Mule Spawn Egg"),
    SKELETON_HORSE_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.SKELETON_HORSE_SPAWN_EGG, 0), "Skeleton Horse Spawn Egg"),
    ZOMBIE_HORSE_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.ZOMBIE_HORSE_SPAWN_EGG, 0), "Zombie Horse Spawn Egg"),
    SHULKER_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.SHULKER_SPAWN_EGG, 0), "Shulker Spawn Egg"),
    NPC_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.NPC_SPAWN_EGG, 0), "Npc Spawn Egg"),
    ELDER_GUARDIAN_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.ELDER_GUARDIAN_SPAWN_EGG, 0), "Elder Guardian Spawn Egg"),
    POLAR_BEAR_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.POLAR_BEAR_SPAWN_EGG, 0), "Polar Bear Spawn Egg"),
    LLAMA_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.LLAMA_SPAWN_EGG, 0), "Llama Spawn Egg"),
    VINDICATOR_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.VINDICATOR_SPAWN_EGG, 0), "Vindicator Spawn Egg"),
    EVOKER_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.EVOKER_SPAWN_EGG, 0), "Evoker Spawn Egg"),
    VEX_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.VEX_SPAWN_EGG, 0), "Vex Spawn Egg"),
    ZOMBIE_VILLAGER_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.ZOMBIE_VILLAGER_SPAWN_EGG, 0), "Zombie Villager Spawn Egg"),
    PARROT_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.PARROT_SPAWN_EGG, 0), "Parrot Spawn Egg"),
    TROPICAL_FISH_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.TROPICAL_FISH_SPAWN_EGG, 0), "Tropical Fish Spawn Egg"),
    COD_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.COD_SPAWN_EGG, 0), "Cod Spawn Egg"),
    PUFFERFISH_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.PUFFERFISH_SPAWN_EGG, 0), "Pufferfish Spawn Egg"),
    SALMON_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.SALMON_SPAWN_EGG, 0), "Salmon Spawn Egg"),
    DROWNED_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.DROWNED_SPAWN_EGG, 0), "Drowned Spawn Egg"),
    DOLPHIN_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.DOLPHIN_SPAWN_EGG, 0), "Dolphin Spawn Egg"),
    TURTLE_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.TURTLE_SPAWN_EGG, 0), "Turtle Spawn Egg"),
    PHANTOM_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.PHANTOM_SPAWN_EGG, 0), "Phantom Spawn Egg"),
    AGENT_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.AGENT_SPAWN_EGG, 0), "Agent Spawn Egg"),
    CAT_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.CAT_SPAWN_EGG, 0), "Cat Spawn Egg"),
    PANDA_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.PANDA_SPAWN_EGG, 0), "Panda Spawn Egg"),
    FOX_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.FOX_SPAWN_EGG, 0), "Fox Spawn Egg"),
    PILLAGER_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.PILLAGER_SPAWN_EGG, 0), "Pillager Spawn Egg"),
    WANDERING_TRADER_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.WANDERING_TRADER_SPAWN_EGG, 0), "Wandering Trader Spawn Egg"),
    RAVAGER_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.RAVAGER_SPAWN_EGG, 0), "Ravager Spawn Egg"),
    BEE_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.BEE_SPAWN_EGG, 0), "Bee Spawn Egg"),
    STRIDER_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.STRIDER_SPAWN_EGG, 0), "Strider Spawn Egg"),
    HOGLIN_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.HOGLIN_SPAWN_EGG, 0), "Hoglin Spawn Egg"),
    PIGLIN_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.PIGLIN_SPAWN_EGG, 0), "Piglin Spawn Egg"),
    ZOGLIN_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.ZOGLIN_SPAWN_EGG, 0), "Zoglin Spawn Egg"),
    PIGLIN_BRUTE_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.PIGLIN_BRUTE_SPAWN_EGG, 0), "Piglin Brute Spawn Egg"),
    AXOLOTL_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.AXOLOTL_SPAWN_EGG, 0), "Axolotl Spawn Egg"),
    GOAT_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.GOAT_SPAWN_EGG, 0), "Goat Spawn Egg"),
    GLOW_SQUID_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.GLOW_SQUID_SPAWN_EGG, 0), "Glow Squid Spawn Egg"),
    GLOW_INK_SAC: new Item(new ItemIdentifier(ItemIds.GLOW_INK_SAC, 0), "Glow Ink Sac"),
    COPPER_INGOT: new Item(new ItemIdentifier(ItemIds.COPPER_INGOT, 0), "Copper Ingot"),
    RAW_IRON: new Item(new ItemIdentifier(ItemIds.RAW_IRON, 0), "Raw Iron"),
    RAW_GOLD: new Item(new ItemIdentifier(ItemIds.RAW_GOLD, 0), "Raw Gold"),
    RAW_COPPER: new Item(new ItemIdentifier(ItemIds.RAW_COPPER, 0), "Raw Copper"),
    EXPERIENCE_BOTTLE: new Item(new ItemIdentifier(ItemIds.EXPERIENCE_BOTTLE, 0), "Experience Bottle"),
    FIRE_CHARGE: new Item(new ItemIdentifier(ItemIds.FIRE_CHARGE, 0), "Fire Charge"),
    WRITABLE_BOOK: new Item(new ItemIdentifier(ItemIds.WRITABLE_BOOK, 0), "Writable Book"),
    WRITTEN_BOOK: new Item(new ItemIdentifier(ItemIds.WRITTEN_BOOK, 0), "Written Book"),
    EMERALD: new Item(new ItemIdentifier(ItemIds.EMERALD, 0), "Emerald"),
    FRAME: new Item(new ItemIdentifier(ItemIds.FRAME, 0), "Frame"),
    FLOWER_POT: new Item(new ItemIdentifier(ItemIds.FLOWER_POT, 0), "Flower Pot"),
    EMPTY_MAP: new Item(new ItemIdentifier(ItemIds.EMPTY_MAP, 0), "Empty Map"),
    SKULL: new Item(new ItemIdentifier(ItemIds.SKULL, 0), "Skull"),
    CARROT_ON_A_STICK: new Item(new ItemIdentifier(ItemIds.CARROT_ON_A_STICK, 0), "Carrot On A Stick"),
    NETHER_STAR: new Item(new ItemIdentifier(ItemIds.NETHER_STAR, 0), "Nether Star"),
    FIREWORK_ROCKET: new Item(new ItemIdentifier(ItemIds.FIREWORK_ROCKET, 0), "Firework Rocket"),
    FIREWORK_STAR: new Item(new ItemIdentifier(ItemIds.FIREWORK_STAR, 0), "Firework Star"),
    ENCHANTED_BOOK: new Item(new ItemIdentifier(ItemIds.ENCHANTED_BOOK, 0), "Enchanted Book"),
    COMPARATOR: new Item(new ItemIdentifier(ItemIds.COMPARATOR, 0), "Comparator"),
    NETHERBRICK: new Item(new ItemIdentifier(ItemIds.NETHERBRICK, 0), "Netherbrick"),
    QUARTZ: new Item(new ItemIdentifier(ItemIds.QUARTZ, 0), "Quartz"),
    TNT_MINECART: new Item(new ItemIdentifier(ItemIds.TNT_MINECART, 0), "Tnt Minecart"),
    HOPPER_MINECART: new Item(new ItemIdentifier(ItemIds.HOPPER_MINECART, 0), "Hopper Minecart"),
    HOPPER: new Item(new ItemIdentifier(ItemIds.HOPPER, 0), "Hopper"),
    RABBIT_FOOT: new Item(new ItemIdentifier(ItemIds.RABBIT_FOOT, 0), "Rabbit Foot"),
    RABBIT_HIDE: new Item(new ItemIdentifier(ItemIds.RABBIT_HIDE, 0), "Rabbit Hide"),
    LEATHER_HORSE_ARMOR: new Item(new ItemIdentifier(ItemIds.LEATHER_HORSE_ARMOR, 0), "Leather Horse Armor"),
    IRON_HORSE_ARMOR: new Item(new ItemIdentifier(ItemIds.IRON_HORSE_ARMOR, 0), "Iron Horse Armor"),
    GOLDEN_HORSE_ARMOR: new Item(new ItemIdentifier(ItemIds.GOLDEN_HORSE_ARMOR, 0), "Golden Horse Armor"),
    DIAMOND_HORSE_ARMOR: new Item(new ItemIdentifier(ItemIds.DIAMOND_HORSE_ARMOR, 0), "Diamond Horse Armor"),
    MUSIC_DISC_13: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_13, 0), "Music Disc 13"),
    MUSIC_DISC_CAT: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_CAT, 0), "Music Disc Cat"),
    MUSIC_DISC_BLOCKS: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_BLOCKS, 0), "Music Disc Blocks"),
    MUSIC_DISC_CHIRP: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_CHIRP, 0), "Music Disc Chirp"),
    MUSIC_DISC_FAR: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_FAR, 0), "Music Disc Far"),
    MUSIC_DISC_MALL: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_MALL, 0), "Music Disc Mall"),
    MUSIC_DISC_MELLOHI: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_MELLOHI, 0), "Music Disc Mellohi"),
    MUSIC_DISC_STAL: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_STAL, 0), "Music Disc Stal"),
    MUSIC_DISC_STRAD: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_STRAD, 0), "Music Disc Strad"),
    MUSIC_DISC_WARD: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_WARD, 0), "Music Disc Ward"),
    MUSIC_DISC_11: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_11, 0), "Music Disc 11"),
    MUSIC_DISC_WAIT: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_WAIT, 0), "Music Disc Wait"),
    TRIDENT: new Item(new ItemIdentifier(ItemIds.TRIDENT, 0), "Trident"),
    LEAD: new Item(new ItemIdentifier(ItemIds.LEAD, 0), "Lead"),
    NAME_TAG: new Item(new ItemIdentifier(ItemIds.NAME_TAG, 0), "Name Tag"),
    PRISMARINE_CRYSTALS: new Item(new ItemIdentifier(ItemIds.PRISMARINE_CRYSTALS, 0), "Prismarine Crystals"),
    MUTTON: new Item(new ItemIdentifier(ItemIds.MUTTON, 0), "Mutton"),
    COOKED_MUTTON: new Item(new ItemIdentifier(ItemIds.COOKED_MUTTON, 0), "Cooked Mutton"),
    ARMOR_STAND: new Item(new ItemIdentifier(ItemIds.ARMOR_STAND, 0), "Armor Stand"),
    SPRUCE_DOOR: new Item(new ItemIdentifier(ItemIds.SPRUCE_DOOR, 0), "Spruce Door"),
    BIRCH_DOOR: new Item(new ItemIdentifier(ItemIds.BIRCH_DOOR, 0), "Birch Door"),
    JUNGLE_DOOR: new Item(new ItemIdentifier(ItemIds.JUNGLE_DOOR, 0), "Jungle Door"),
    ACACIA_DOOR: new Item(new ItemIdentifier(ItemIds.ACACIA_DOOR, 0), "Acacia Door"),
    DARK_OAK_DOOR: new Item(new ItemIdentifier(ItemIds.DARK_OAK_DOOR, 0), "Dark Oak Door"),
    CHORUS_FRUIT: new Item(new ItemIdentifier(ItemIds.CHORUS_FRUIT, 0), "Chorus Fruit"),
    POPPED_CHORUS_FRUIT: new Item(new ItemIdentifier(ItemIds.POPPED_CHORUS_FRUIT, 0), "Popped Chorus Fruit"),
    DRAGON_BREATH: new Item(new ItemIdentifier(ItemIds.DRAGON_BREATH, 0), "Dragon Breath"),
    SPLASH_POTION: new Item(new ItemIdentifier(ItemIds.SPLASH_POTION, 0), "Splash Potion"),
    LINGERING_POTION: new Item(new ItemIdentifier(ItemIds.LINGERING_POTION, 0), "Lingering Potion"),
    COMMAND_BLOCK_MINECART: new Item(new ItemIdentifier(ItemIds.COMMAND_BLOCK_MINECART, 0), "Command Block Minecart"),
    ELYTRA: new Item(new ItemIdentifier(ItemIds.ELYTRA, 0), "Elytra"),
    PRISMARINE_SHARD: new Item(new ItemIdentifier(ItemIds.PRISMARINE_SHARD, 0), "Prismarine Shard"),
    SHULKER_SHELL: new Item(new ItemIdentifier(ItemIds.SHULKER_SHELL, 0), "Shulker Shell"),
    BANNER: new Item(new ItemIdentifier(ItemIds.BANNER, 0), "Banner"),
    TOTEM_OF_UNDYING: new Item(new ItemIdentifier(ItemIds.TOTEM_OF_UNDYING, 0), "Totem Of Undying"),
    IRON_NUGGET: new Item(new ItemIdentifier(ItemIds.IRON_NUGGET, 0), "Iron Nugget"),
    NAUTILUS_SHELL: new Item(new ItemIdentifier(ItemIds.NAUTILUS_SHELL, 0), "Nautilus Shell"),
    HEART_OF_THE_SEA: new Item(new ItemIdentifier(ItemIds.HEART_OF_THE_SEA, 0), "Heart Of The Sea"),
    SCUTE: new Item(new ItemIdentifier(ItemIds.SCUTE, 0), "Scute"),
    TURTLE_HELMET: new Item(new ItemIdentifier(ItemIds.TURTLE_HELMET, 0), "Turtle Helmet"),
    PHANTOM_MEMBRANE: new Item(new ItemIdentifier(ItemIds.PHANTOM_MEMBRANE, 0), "Phantom Membrane"),
    CROSSBOW: new Item(new ItemIdentifier(ItemIds.CROSSBOW, 0), "Crossbow"),
    SPRUCE_SIGN: new Item(new ItemIdentifier(ItemIds.SPRUCE_SIGN, 0), "Spruce Sign"),
    BIRCH_SIGN: new Item(new ItemIdentifier(ItemIds.BIRCH_SIGN, 0), "Birch Sign"),
    JUNGLE_SIGN: new Item(new ItemIdentifier(ItemIds.JUNGLE_SIGN, 0), "Jungle Sign"),
    ACACIA_SIGN: new Item(new ItemIdentifier(ItemIds.ACACIA_SIGN, 0), "Acacia Sign"),
    DARK_OAK_SIGN: new Item(new ItemIdentifier(ItemIds.DARK_OAK_SIGN, 0), "Dark Oak Sign"),
    FLOWER_BANNER_PATTERN: new Item(new ItemIdentifier(ItemIds.FLOWER_BANNER_PATTERN, 0), "Flower Banner Pattern"),
    CREEPER_BANNER_PATTERN: new Item(new ItemIdentifier(ItemIds.CREEPER_BANNER_PATTERN, 0), "Creeper Banner Pattern"),
    SKULL_BANNER_PATTERN: new Item(new ItemIdentifier(ItemIds.SKULL_BANNER_PATTERN, 0), "Skull Banner Pattern"),
    MOJANG_BANNER_PATTERN: new Item(new ItemIdentifier(ItemIds.MOJANG_BANNER_PATTERN, 0), "Mojang Banner Pattern"),
    FIELD_MASONED_BANNER_PATTERN: new Item(new ItemIdentifier(ItemIds.FIELD_MASONED_BANNER_PATTERN, 0), "Field Masoned Banner Pattern"),
    BORDURE_INDENTED_BANNER_PATTERN: new Item(new ItemIdentifier(ItemIds.BORDURE_INDENTED_BANNER_PATTERN, 0), "Bordure Indented Banner Pattern"),
    PIGLIN_BANNER_PATTERN: new Item(new ItemIdentifier(ItemIds.PIGLIN_BANNER_PATTERN, 0), "Piglin Banner Pattern"),
    GLOBE_BANNER_PATTERN: new Item(new ItemIdentifier(ItemIds.GLOBE_BANNER_PATTERN, 0), "Globe Banner Pattern"),
    CAMPFIRE: new Item(new ItemIdentifier(ItemIds.CAMPFIRE, 0), "Campfire"),
    SUSPICIOUS_STEW: new Item(new ItemIdentifier(ItemIds.SUSPICIOUS_STEW, 0), "Suspicious Stew"),
    HONEYCOMB: new Item(new ItemIdentifier(ItemIds.HONEYCOMB, 0), "Honeycomb"),
    HONEY_BOTTLE: new Item(new ItemIdentifier(ItemIds.HONEY_BOTTLE, 0), "Honey Bottle"),
    CAMERA: new Item(new ItemIdentifier(ItemIds.CAMERA, 0), "Camera"),
    COMPOUND: new Item(new ItemIdentifier(ItemIds.COMPOUND, 0), "Compound"),
    ICE_BOMB: new Item(new ItemIdentifier(ItemIds.ICE_BOMB, 0), "Ice Bomb"),
    BLEACH: new Item(new ItemIdentifier(ItemIds.BLEACH, 0), "Bleach"),
    RAPID_FERTILIZER: new Item(new ItemIdentifier(ItemIds.RAPID_FERTILIZER, 0), "Rapid Fertilizer"),
    BALLOON: new Item(new ItemIdentifier(ItemIds.BALLOON, 0), "Balloon"),
    MEDICINE: new Item(new ItemIdentifier(ItemIds.MEDICINE, 0), "Medicine"),
    SPARKLER: new Item(new ItemIdentifier(ItemIds.SPARKLER, 0), "Sparkler"),
    GLOW_STICK: new Item(new ItemIdentifier(ItemIds.GLOW_STICK, 0), "Glow Stick"),
    LODESTONE_COMPASS: new Item(new ItemIdentifier(ItemIds.LODESTONE_COMPASS, 0), "Lodestone Compass"),
    NETHERITE_INGOT: new Item(new ItemIdentifier(ItemIds.NETHERITE_INGOT, 0), "Netherite Ingot"),
    NETHERITE_SWORD: new Item(new ItemIdentifier(ItemIds.NETHERITE_SWORD, 0), "Netherite Sword"),
    NETHERITE_SHOVEL: new Item(new ItemIdentifier(ItemIds.NETHERITE_SHOVEL, 0), "Netherite Shovel"),
    NETHERITE_PICKAXE: new Item(new ItemIdentifier(ItemIds.NETHERITE_PICKAXE, 0), "Netherite Pickaxe"),
    NETHERITE_AXE: new Item(new ItemIdentifier(ItemIds.NETHERITE_AXE, 0), "Netherite Axe"),
    NETHERITE_HOE: new Item(new ItemIdentifier(ItemIds.NETHERITE_HOE, 0), "Netherite Hoe"),
    NETHERITE_HELMET: new Item(new ItemIdentifier(ItemIds.NETHERITE_HELMET, 0), "Netherite Helmet"),
    NETHERITE_CHESTPLATE: new Item(new ItemIdentifier(ItemIds.NETHERITE_CHESTPLATE, 0), "Netherite Chestplate"),
    NETHERITE_LEGGINGS: new Item(new ItemIdentifier(ItemIds.NETHERITE_LEGGINGS, 0), "Netherite Leggings"),
    NETHERITE_BOOTS: new Item(new ItemIdentifier(ItemIds.NETHERITE_BOOTS, 0), "Netherite Boots"),
    NETHERITE_SCRAP: new Item(new ItemIdentifier(ItemIds.NETHERITE_SCRAP, 0), "Netherite Scrap"),
    CRIMSON_SIGN: new Item(new ItemIdentifier(ItemIds.CRIMSON_SIGN, 0), "Crimson Sign"),
    WARPED_SIGN: new Item(new ItemIdentifier(ItemIds.WARPED_SIGN, 0), "Warped Sign"),
    CRIMSON_DOOR: new Item(new ItemIdentifier(ItemIds.CRIMSON_DOOR, 0), "Crimson Door"),
    WARPED_DOOR: new Item(new ItemIdentifier(ItemIds.WARPED_DOOR, 0), "Warped Door"),
    WARPED_FUNGUS_ON_A_STICK: new Item(new ItemIdentifier(ItemIds.WARPED_FUNGUS_ON_A_STICK, 0), "Warped Fungus On A Stick"),
    CHAIN: new Item(new ItemIdentifier(ItemIds.CHAIN, 0), "Chain"),
    MUSIC_DISC_PIGSTEP: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_PIGSTEP, 0), "Music Disc Pigstep"),
    NETHER_SPROUTS: new Item(new ItemIdentifier(ItemIds.NETHER_SPROUTS, 0), "Nether Sprouts"),
    SOUL_CAMPFIRE: new Item(new ItemIdentifier(ItemIds.SOUL_CAMPFIRE, 0), "Soul Campfire"),
    GLOW_FRAME: new Item(new ItemIdentifier(ItemIds.GLOW_FRAME, 0), "Glow Frame"),
    GOAT_HORN: new Item(new ItemIdentifier(ItemIds.GOAT_HORN, 0), "Goat Horn"),
    AMETHYST_SHARD: new Item(new ItemIdentifier(ItemIds.AMETHYST_SHARD, 0), "Amethyst Shard"),
    SPYGLASS: new Item(new ItemIdentifier(ItemIds.SPYGLASS, 0), "Spyglass"),
    MUSIC_DISC_OTHERSIDE: new Item(new ItemIdentifier(ItemIds.MUSIC_DISC_OTHERSIDE, 0), "Music Disc Otherside"),
    FROG_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.FROG_SPAWN_EGG, 0), "Frog Spawn Egg"),
    TADPOLE_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.TADPOLE_SPAWN_EGG, 0), "Tadpole Spawn Egg"),
    TADPOLE_BUCKET: new Item(new ItemIdentifier(ItemIds.TADPOLE_BUCKET, 0), "Tadpole Bucket"),
    ALLAY_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.ALLAY_SPAWN_EGG, 0), "Allay Spawn Egg"),
    FIREFLY_SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.FIREFLY_SPAWN_EGG, 0), "Firefly Spawn Egg"),
    BOAT: new Item(new ItemIdentifier(ItemIds.BOAT, 0), "Boat"),
    DYE: new Item(new ItemIdentifier(ItemIds.DYE, 0), "Dye"),
    BANNER_PATTERN: new Item(new ItemIdentifier(ItemIds.BANNER_PATTERN, 0), "Banner Pattern"),
    SPAWN_EGG: new Item(new ItemIdentifier(ItemIds.SPAWN_EGG, 0), "Spawn Egg"),
    END_CRYSTAL: new Item(new ItemIdentifier(ItemIds.END_CRYSTAL, 0), "End Crystal"),
    GLOW_BERRIES: new Item(new ItemIdentifier(ItemIds.GLOW_BERRIES, 0), "Glow Berries"),
}