name: AdvancedPurification
author: Zwuiix
api: 4.0.0
version: 1.0.0
main: Zwuiix\AdvancedPurification\Main
description: Made by Zwuiix

permissions:
  advancedpurification.boost:
    default: op
    description: Boost Permissions